### PR TITLE
Fix broken links to LL and LR parsing lectures

### PR DESCRIPTION
**Pull request by jasperdenkers**
The links on http://tudelft-in4303.github.io/lectures/ to the LL and LR parsing lectures don't work.

### CODE REVIEW

**Comment by milosonator** [comment]
Somehow these changes are not yet reflected on the actual github.io site.

**Comment by martijndwars** [comment]
They are on my machine. Try hard-refreshing the page (probably a caching thing)

**Comment by milosonator** [comment]
Tried that, didn't help. Different browser, same thing. Used WGET to get the HTML, same problem. Interesting.

**Comment by milosonator** [comment]
I'm not a Jekyll expert but shouldn't these two files be renamed to uppercase LL and LR:
https://github.com/TUDelft-IN4303/TUDelft-IN4303.github.io/tree/master/lectures/generation
 and update the links on the main lecture page also to uppercase LL and LR?
https://github.com/TUDelft-IN4303/TUDelft-IN4303.github.io/blob/master/lectures/index.md

**Comment by jasperdenkers** [comment]
@milosonator I guess you were trying to reach the page trough the menu (instead of http://tudelft-in4303.github.io/lectures/ which this PR fixed), see #16.

**Comment by milosonator** [comment]
+1

**Comment by martijndwars** [comment]
Right, thanks guys!

**Pull request merged**
